// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZpocao02yX0T1sM7XGwGYxcART6iiyR0',
    appId: '1:954354662946:web:bf7f4977fb976130d8d47b',
    messagingSenderId: '954354662946',
    projectId: 'testdb-3b42e',
    authDomain: 'testdb-3b42e.firebaseapp.com',
    databaseURL: 'https://testdb-3b42e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testdb-3b42e.firebasestorage.app',
    measurementId: 'G-1HKSJ5FRNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGnj3HsnIPKMzSRatPWteMUXkiqUfNbks',
    appId: '1:954354662946:android:338843b9c59cf950d8d47b',
    messagingSenderId: '954354662946',
    projectId: 'testdb-3b42e',
    databaseURL: 'https://testdb-3b42e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testdb-3b42e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzNcTa7onoqaFspB3O5rgv-NrkvIL-iqc',
    appId: '1:954354662946:ios:3624079a23a3ab26d8d47b',
    messagingSenderId: '954354662946',
    projectId: 'testdb-3b42e',
    databaseURL: 'https://testdb-3b42e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testdb-3b42e.firebasestorage.app',
    iosBundleId: 'com.example.proyectoAppPabloCasado',
  );
}
